//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSimpleApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WManagerEntities : DbContext
    {
        public WManagerEntities()
            : base("name=WManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<wmproject> wmprojects { get; set; }
        public virtual DbSet<wmprojectaccess> wmprojectaccesses { get; set; }
        public virtual DbSet<wmrole> wmroles { get; set; }
        public virtual DbSet<wmsprint> wmsprints { get; set; }
        public virtual DbSet<wmtask> wmtasks { get; set; }
        public virtual DbSet<wmtoken> wmtokens { get; set; }
        public virtual DbSet<wmuser> wmusers { get; set; }
    }
}
