//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSimpleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmprojectaccess
    {
        public int id { get; set; }
        public string project_id { get; set; }
        public Nullable<int> users_id { get; set; }
    
        public virtual wmproject wmproject { get; set; }
        public virtual wmuser wmuser { get; set; }
    }
}
