//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSimpleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmtask
    {
        public int id { get; set; }
        public Nullable<int> id_sprint { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<double> time_estimate { get; set; }
        public Nullable<double> time_worked { get; set; }
        public Nullable<double> time_remaining { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_req { get; set; }
    
        public virtual wmsprint wmsprint { get; set; }
    }
}
