//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSimpleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmtoken
    {
        public int id { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual wmuser wmuser { get; set; }
    }
}
