//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetSimpleApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class wmuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wmuser()
        {
            this.wmprojectaccesses = new HashSet<wmprojectaccess>();
            this.wmtokens = new HashSet<wmtoken>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string route_img { get; set; }
        public string reset_password_token { get; set; }
        public Nullable<System.DateTime> reset_password_expires { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> role_id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wmprojectaccess> wmprojectaccesses { get; set; }
        public virtual wmrole wmrole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wmtoken> wmtokens { get; set; }
    }
}
